name:                AutomatedReasoning
version:             0.1.0.0
github:              "aromazyl/AutomatedReasoning"
license:             BSD3
author:              "zhangyule"
maintainer:          "zyl2336709@gmail.com"
copyright:           "MIT License"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/aromazyl/AutomatedReasoning#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  AutomatedReasoning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AutomatedReasoning

tests:
  AutomatedReasoning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AutomatedReasoning
